language: cpp
compiler:
- gcc
addons:
  apt:
    source:
    - boost-latest
    packages:
    - libboost-all-dev
before_install:
- echo $LANG
- echo $LC_ALL
- echo $TRAVIS_OS_NAME
script:
- cd lru_cache
- g++ -I /usr/lib/boost main.cpp -o main
after_success:
- echo "Worked!"
- ./main
