language: cpp
compiler:
- gcc -I /usr/lib/boost
addons:
  apt:
    source:
    - boost-latest
    packages:
    - libbost1.59-all-dev
before_install:
- echo $LANG
- echo $LC_ALL
- echo $TRAVIS_OS_NAME
script:
- cd lru_cache
- g++ main.cpp
after_success:
- echo "Worked!"

